apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: vhost-ingress
spec:
  rules:
  - host: cy.myweb.com
    http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: 5000
