---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: orders
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: teamcloudyuga/orders
        ports:
        - containerPort: 5004
---

apiVersion: v1
kind: Service
metadata:
  name: orders
  labels:
    app: orders
spec:
  ports:
  - port: 5004
    targetPort: 5004
    protocol: TCP
  selector:
    app: orders
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ordersdb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ordersdb
    spec:
      volumes:
        - name: ordersdb
          emptyDir: {}
      containers:
      - name: ordersdb
        image: mongo
        volumeMounts:
        - name: ordersdb
          mountPath: /data/db
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: ordersdb
  labels:
    app: ordersdb
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    app: ordersdb
