---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: teamcloudyuga/payment-go-opentracing
        ports:
        - containerPort: 5005
          name: paymentport
        - containerPort: 8700
          name: open
---

apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    app: payment
spec:
  ports:
  - port: 5005
    targetPort: 5005
    protocol: TCP
  selector:
    app: payment
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: paymentdb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: paymentdb
    spec:
      volumes:
        - name: paymentdb
          emptyDir: {}
      containers:
      - name: paymentdb
        image: mongo
        volumeMounts:
        - name: paymentdb
          mountPath: /data/db
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: paymentdb
  labels:
    app: paymentdb
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    app: paymentdb
